apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.namespace }}
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
