apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.namespace }}
  name: booktitle
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.env.host }}
    http:
      paths:
      - path: /booktitles
        pathType: Prefix
        backend:
          service:
            name: booktitle
            port: 
              number: 80