apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.namespace }}
  name: provisioning
spec:
  type: ClusterIP
  selector:
    app: provisioning
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80