apiVersion: v1
kind: Service
metadata:
  name: course
  namespace: {{ .Release.namespace }}
spec:
  type: ClusterIP
  selector:
    app: course
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80